# Generated by Django 2.2.5 on 2019-09-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livraria',
            new_name='Livro',
        ),
    ]
