# Generated by Django 2.2.5 on 2019-09-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='descricaoProduto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compras',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='compras',
            name='qtdPrevistoMes',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
